import type { Metadata } from "next";
import NavBar from "@/components/NavBar/NavBar";
import NewNavBar from "@/components/NewNavBar/NewNavBar";
import NavbarYariv from "@/components/NavbarYariv/NavbarYariv";



export const metadata: Metadata = {
  title: "Roey's work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         {/* <NavBar/> */}
         <NewNavBar/>
         {/* <NavbarYariv/> */}
        {children}
      </body>
    </html>
  );
}
